name = "biccame-musume"
compatibility_date = "2025-07-12"
compatibility_flags = ["nodejs_compat_v2"]
main = "src/index.ts"
routes = [{ pattern = "biccame-musume.com", custom_domain = true }]

[env.prod]
name = "biccame-musume-prod"
workers_dev = false
preview_urls = false
routes = [{ pattern = "biccame-musume.com", custom_domain = true }]

[env.dev]
name = "biccame-musume-dev"
workers_dev = true
preview_urls = true
routes = [{ pattern = "biccame-musume-dev.com", custom_domain = true }]

[env.prod.assets]
directory = "dist"
not_found_handling = "single-page-application"
binding = "ASSETS"

[[env.prod.kv_namespaces]]
binding = "VOTES"
id = "04dd77043cc240b2b8bbbd7f0adfd67d"

[[env.prod.kv_namespaces]]
binding = "BICCAME_MUSUME_EVENTS"
id = "ef49185c58d04a0790e7c68394d78089"

[env.prod.vars]
CF_ACCESS_TEAM_DOMAIN = "tkgstrator.cloudflareaccess.com"
CF_ACCESS_AUD = "35f179c635cc0393185304d0d7cbaf64a720bc164479a0df06f5567b7375b3d1"

[env.dev.assets]
directory = "dist"
not_found_handling = "single-page-application"
binding = "ASSETS"

[[env.dev.kv_namespaces]]
binding = "VOTES"
id = "97c756ffdc3e4e2596946a57092d9b2d"

[[env.dev.kv_namespaces]]
binding = "BICCAME_MUSUME_EVENTS"
id = "6f3b7b710eb646a0aef7ab524609bb67"

[env.dev.vars]
CF_ACCESS_TEAM_DOMAIN = "tkgstrator.cloudflareaccess.com"
CF_ACCESS_AUD = "35f179c635cc0393185304d0d7cbaf64a720bc164479a0df06f5567b7375b3d1"

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true

[[ratelimits]]
name = "RATE_LIMITER"
namespace_id = "1001"
simple = { limit = 50, period = 60 }

[[env.dev.ratelimits]]
name = "RATE_LIMITER"
namespace_id = "1001"
simple = { limit = 50, period = 60 }

[[env.prod.ratelimits]]
name = "RATE_LIMITER"
namespace_id = "1001"
simple = { limit = 50, period = 60 }
