name = "biccame-musume"
compatibility_date = "2025-07-12"
compatibility_flags = ["nodejs_compat_v2"]
main = "src/index.ts"
routes = [{ pattern = "biccame-musume.com", custom_domain = true }]

[env.prod]
name = "biccame-musume-prod"
workers_dev = false
preview_urls = false
routes = [{ pattern = "biccame-musume.com", custom_domain = true }]

[env.dev]
name = "biccame-musume-dev"
workers_dev = true
preview_urls = true
routes = [{ pattern = "biccame-musume-dev.com", custom_domain = true }]

[env.prod.assets]
directory = "dist"
not_found_handling = "single-page-application"
binding = "ASSETS"
# run_worker_first = ["/sitemap.xml", "/robots.txt"]

[[env.prod.kv_namespaces]]
binding = "VOTES"
id = "04dd77043cc240b2b8bbbd7f0adfd67d"

[env.dev.assets]
directory = "dist"
not_found_handling = "single-page-application"
binding = "ASSETS"
# run_worker_first = ["/sitemap.xml", "/robots.txt"]

[[env.dev.kv_namespaces]]
binding = "VOTES"
id = "97c756ffdc3e4e2596946a57092d9b2d"
