name: Continuous Integration
on:
  push:
jobs:
  commitlint:
    name: CommitLint
    if: github.event.action != 'closed' || github.event.pull_request.merged != true
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-
      - name: Install dependencies
        run: bun install --frozen-lockfile --ignore-scripts
      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: bun commitlint --last --verbose
      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: bun commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
  check:
    name: Code Check
    runs-on: ubuntu-24.04
    if: github.event.action != 'closed' || github.event.pull_request.merged != true
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-
      - name: Install dependencies
        run: bun install --frozen-lockfile --ignore-scripts
      - name: Check
        run: |
          bun biome check src __tests__
  test:
    name: Test
    runs-on: ubuntu-24.04
    if: github.event.action != 'closed' || github.event.pull_request.merged != true
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-
      - name: Install dependencies
        run: bun install --frozen-lockfile --ignore-scripts
      - name: Test
        run: |
          bun test
  tsc:
    name: Compile TypeScript
    runs-on: ubuntu-24.04
    if: github.event.action != 'closed' || github.event.pull_request.merged != true
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-
      - name: Install dependencies
        run: bun install --frozen-lockfile --ignore-scripts
      - name: Test
        run: |
          bun tsc --noEmit
